set(_CATKIN_CURRENT_PACKAGE "rqt_mavros_gui")
set(rqt_mavros_gui_VERSION "0.0.0")
set(rqt_mavros_gui_MAINTAINER "ros <ros@todo.todo>")
set(rqt_mavros_gui_PACKAGE_FORMAT "1")
set(rqt_mavros_gui_BUILD_DEPENDS )
set(rqt_mavros_gui_BUILD_EXPORT_DEPENDS "mavros" "mavros_msgs" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_mavros_gui_BUILDTOOL_DEPENDS "catkin")
set(rqt_mavros_gui_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_mavros_gui_EXEC_DEPENDS "mavros" "mavros_msgs" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_mavros_gui_RUN_DEPENDS "mavros" "mavros_msgs" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_mavros_gui_TEST_DEPENDS )
set(rqt_mavros_gui_DOC_DEPENDS )
set(rqt_mavros_gui_URL_WEBSITE "")
set(rqt_mavros_gui_URL_BUGTRACKER "")
set(rqt_mavros_gui_URL_REPOSITORY "")
set(rqt_mavros_gui_DEPRECATED "")