set(rqt_mavros_gui_SETUP_PY_SETUP_MODULE "distutils.core")
set(rqt_mavros_gui_SETUP_PY_VERSION "0.0.0")
set(rqt_mavros_gui_SETUP_PY_SCRIPTS "")
set(rqt_mavros_gui_SETUP_PY_PACKAGES "rqt_mavros_gui")
set(rqt_mavros_gui_SETUP_PY_PACKAGE_DIRS "src/rqt_mavros_gui")
set(rqt_mavros_gui_SETUP_PY_MODULES "")
set(rqt_mavros_gui_SETUP_PY_MODULE_DIRS "")